### ISSUE TITLE
Compilation error in Visual Studio 2013

### ISSUE THREAD

**Issue by olivierbichler-cea** [tronkko/dirent#13]
Hi,

I have the following error on Visual Studio 2013, since the addition of scandir():

C:\projects\dirent\include\dirent.h(917): error C2440: '=' : cannot convert from 'void *' to 'dirent **' [C:\projects\n2d2\build\N2D2-OS.vcxproj]
          Conversion from 'void*' to pointer to non-'void' requires an explicit cast
C:\projects\dirent\include\dirent.h(968): error C2664: 'void qsort(void *,size_t,size_t,int (__cdecl *)(const void *,const void *))' : cannot convert argument 4 from 'void *' to 'int (__cdecl *)(const void *,const void *)' [C:\projects\n2d2\build\N2D2-OS.vcxproj]

**Comment by suzhengpeng** [comment]
I got the same with you~ 囧

**Comment by leoz** [comment]
Got the same issue with VS 2017. Cannot use dirent anymore :(

**Comment by tronkko** [comment]
Thanks for your comments!  Please try the fix and reopen this ticket if the problem still persists.
