### ISSUE TITLE
error C2440: "=": Can not convert from "void *" to "dirent **"

### ISSUE THREAD

**Issue by suzhengpeng** [tronkko/dirent#14]
Visual Studio 2017 && Windows 10
---
error C2440: "=": Can not convert from "void *" to "dirent **"
error C2664: "void qsort (void *, :: size_t, :: size_t, _CoreCrtNonSecureSearchSortCompareFunction)": Can not convert parameter 4 from "void *" to "_CoreCrtNonSecureSearchSortCompareFunction"

When I use your .h in my project , the vs2017 said like it . I don't know what's the matter with it...

**Comment by leoz** [comment]
Got the same issue...

**Comment by stweyel** [comment]
dito

**Comment by leoz** [comment]
Apparently it was fixed in a fork here: https://github.com/cjhoward/dirent
Maybe somebody could incorporate it into mainline.

**Comment by tronkko** [comment]
Thanks for your comments!  Please try the fix and reopen this ticket if the problem still persists.

**Comment by suzhengpeng** [comment]
Thks for you fix it. I will test the new one late.

发件人: Leonid Zolotarev
发送时间: 2017年9月18日 20:31
收件人: tronkko/dirent
抄送: ZhengPeng SU; Author
主题: Re: [tronkko/dirent] error C2440: "=": Can not convert from "void *"to "dirent **" (#14)

Apparently it was fixed in a fork here: https://github.com/cjhoward/dirent
Maybe somebody could incorporate it into mainline.
