### ISSUE TITLE
not well support chinese os

### ISSUE THREAD

**Issue by smartsl** [tronkko/dirent#17]
only get d_type(0) and d_name('?') with chinese file names.

**Comment by smartsl** [comment]
i changed readdir to _wreaddir, which fixed it.

**Comment by tronkko** [comment]
Could you please provide a zip or tar package with some chinese file names to aid further development? The files may be empty, only the file names matter.

**Comment by smartsl** [comment]
I think any UNICODE character can be a problem, not only Chinese.
This is an example: "测试"(which means "test" in Chinese).

I got it done by using _wreaddir and other wchar_t functions, which should be emphasized in docs.
