### ISSUE TITLE
Japanese Filenames in large folders get returned as ?

### ISSUE THREAD

**Issue by Arkanipro** [tronkko/dirent#18]
If I try reading Japanese filenames in small directories theres no problem.
But as I do it in a folder with 800 files+ the type of files including Japanese chars is 0 and the name is ?

**Comment by Arkanipro** [comment]
[Filenames](https://drive.google.com/open?id=1sspl3xCVHqpUldV9QwahE-_dDIgMLcEE)
The type of this files is 0 and they're name is ? and I can guarantee that this files work just fine.
As I copy these files into another directory it recognizes these files but with different names: [Filenames](https://drive.google.com/open?id=1wkq6-2wzhI1u56pYnT4KCdNnqE9oYFHI).
I don't know how windows handles these filenames but it's super weird to me.
best regards Arkanipro

**Comment by tronkko** [comment]
Could you also confirm with dir /x command that the files do have traditional 8+3 file names.  Perhaps the files were stored on a disk which did not support 8+3 file names.

**Comment by Arkanipro** [comment]
Thank you for solving my problem and I am also sorry, because I didn't know the library well.
Using _wopendir and _wreaddir solved my problem
Thanks
