### ISSUE TITLE
Version info in dirent-1.23.2 release

### ISSUE THREAD

**Issue by c72578** [tronkko/dirent#23]
The version info in
`src/dirent.h`
is still at 1.23.1 instead of 1.23.2 in the top comment of the file in case of the released files:
https://github.com/tronkko/dirent/archive/1.23.2.zip
https://github.com/tronkko/dirent/archive/1.23.2.tar.gz
<pre>
/*
 * Dirent interface for Microsoft Visual Studio
 * Version 1.23.1
 *
 * Copyright (C) 2006-2012 Toni Ronkko
 * This file is part of dirent.  Dirent may be freely distributed
 * under the MIT license.  For all details and documentation, see
 * https://github.com/tronkko/dirent
 */
</pre>

This can be corrected in the next release ...

**Comment by tronkko** [comment]
Thanks!  This is fixed in commit c1aa023cf617b5690f4b6ed6e100f3fbb0da44d9 which removes the version label from future releases.
