### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [tronkko/dirent#24]
[An extra null pointer check is not needed](https://stackoverflow.com/questions/18775608/free-a-null-pointer-anyway-or-check-first "Free a null pointer anyway or check first?") in the following functions.
- [opendir](https://github.com/tronkko/dirent/blob/a3e9db58aa4be4972054e77a455c916ffea2e42c/include/dirent.h#L713 "opendir function")
- [scandir](https://github.com/tronkko/dirent/blob/a3e9db58aa4be4972054e77a455c916ffea2e42c/include/dirent.h#L986 "scandir function")
- [_wclosedir](https://github.com/tronkko/dirent/blob/a3e9db58aa4be4972054e77a455c916ffea2e42c/include/dirent.h#L554 "_wclosedir function")

**Comment by tronkko** [comment]
Thanks!  That is really true!  Would you like to change that yourself?

**Comment by tronkko** [comment]
I can do it, no prob.

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/tronkko/dirent/commit/f164d5b101d3c3e903d0810323ee6c64217cae46 "Remove unnecessary null pointer checks").
