### ISSUE TITLE
Reduce source code in dirent_mbstowcs_s()

### ISSUE THREAD

**Issue by elfring** [tronkko/dirent#26]
How do you think about to replace [an if statement at the end of the function “dirent_mbstowcs_s”](https://github.com/tronkko/dirent/blob/a3e9db58aa4be4972054e77a455c916ffea2e42c/include/dirent.h#L1110 "Update candidate") by the shorter statement “`return (n > 0 && flag == 0) ? 0 : 1;`”?

**Comment by tronkko** [comment]
I generally prefer if statement.  I think if statement is more readable and easier to understand.
