### ISSUE TITLE
Update for year number in copyright?

### ISSUE THREAD

**Issue by elfring** [tronkko/dirent#27]
Does a year number need an update in [the copyright information](https://github.com/tronkko/dirent/blob/2666160a6743ebb295c316c1c9d1bb9a1b0b9e5c/include/dirent.h#L4 "Checking copyright details")?

**Comment by tronkko** [comment]
Thanks!

**Comment by elfring** [comment]
Thanks for [another small software update](https://github.com/tronkko/dirent/commit/ee812d43cff8d3aeab3b0200298954b782eb1c47 "Fix copyright year").
