### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [tronkko/dirent#28]
I would like to point out that an identifier like “[`_WDIR`](https://github.com/tronkko/dirent/blob/2666160a6743ebb295c316c1c9d1bb9a1b0b9e5c/include/dirent.h#L234 "Update candidate")” [does eventually not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier "Do not use identifiers which are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by tronkko** [comment]
_WDIR cannot be changed to fit the naming convention as it would break compatibility with existing programs and other dirent implementations such as MinGW.

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoiding undefined behaviour?")?

**Comment by tronkko** [comment]
Little can be done to fix that.  If some automatic tool flags a piece of software using my dirent.h as to depend on undefined behaviour then the obvious solution would be to remove dirent.h from that project and place dirent.h among system headers such as stdio.h.  I believe Cygwin and MinGW also define _WDIR and place their dirent.h among the system headers.  Dirent.h is part of standard library on many unixes so one might make an exception here.

**Comment by elfring** [comment]
* I imagine that the software situation can be adjusted further if sufficient change willingness would evolve.
* Would you like to restrict the safe usage of this source file for [implementation of compilers for the programming languages “C” and “C++”](https://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier#answer-228797 "What are the rules about using an underscore in a C++ identifier?")?
