### ISSUE TITLE
Reduce scope for a few local variables?

### ISSUE THREAD

**Issue by elfring** [tronkko/dirent#29]
A few local variables are declared at the beginning of functions despite of the detail that they are used only a bit later in [these implementations](https://github.com/tronkko/dirent/blob/2666160a6743ebb295c316c1c9d1bb9a1b0b9e5c/include/dirent.h#L665 "Update candidate").
Will it help to [reduce the scope for such variables](https://refactoring.com/catalog/reduceScopeOfVariable.html "Reduce scope of variable")?

**Comment by tronkko** [comment]
You are right, as always :)  Reduction of the scope would improve readability.  However, I like to keep the code compatible with older versions of Visual Studio which did require variables to be declared at the beginning of the block.

**Comment by elfring** [comment]
How would you interpret the beginning of the block for a possible adjustment?

**Comment by tronkko** [comment]
Older compilers just needed an extra block like in commit https://github.com/tronkko/dirent/commit/b33e10caf46df5af65a34660f458f81b3dd2d7ca

**Comment by elfring** [comment]
Thanks for [your small source code adjustment](https://github.com/tronkko/dirent/commit/b33e10caf46df5af65a34660f458f81b3dd2d7ca "Add extra block to reduce variable scope").
