### ISSUE TITLE
MSVC 14.27.29110 Fails to Compile

### ISSUE THREAD

**Issue by mewtwo532** [tronkko/dirent#38]
C2362- Initialization of 'p' is skipped by 'goto exit_closedir' - line 414
C2362 - Initialization of 'ok' is skipped by 'goto exit_failure' - line 760

**Comment by mewtwo532** [comment]
Using Visual Studio Community 2019, fails when attempting to compile C++ this header included.

**Comment by mewtwo532** [comment]
This only occurs with conformance mode on.

**Comment by 1287953547** [comment]
> C2362- Initialization of 'p' is skipped by 'goto exit_closedir' - line 414
> C2362 - Initialization of 'ok' is skipped by 'goto exit_failure' - line 760

me too

**Comment by tronkko** [comment]
Can you verify that this issue is now fixed?

**Comment by mewtwo532** [comment]
Yes, the issue is now fixed. Thank You.
