### ISSUE TITLE
Does it support UTF-8 in filenames?

### ISSUE THREAD

**Issue by ChrisKozmik** [tronkko/dirent#39]
Does it support UTF-8 filenames (regardless of OS version and locale settings)?

**Comment by tronkko** [comment]
You might be interested in wide-character versions of dirent functions.
They work irrespective of the os version and locale.

The single/multibyte versions of the dirent functions expect that directory
names are represented in the currently selected windows codepage and they
return file names expressed in the currently selected codepage, which is
not necessarily UTF-8.



ma 28. kesäk. 2021 klo 15.35 Chris Koźmik ***@***.***>
kirjoitti:

**Comment by ChrisKozmik** [comment]
Do you know if setting locale as UTF-8 would guarantee opendir() (non wide-char version) to work with UTF-8 filenames (it works on my machine)?

std::locale::global(std::locale("LC_CTYPE=.utf8"));

Similarly, does setting locale as UTF-8 would guarantee _wopendir() to work?

**Comment by tronkko** [comment]
Setting locale appears to guarantee that opendir() and fopen() work with UTF-8 file names: Microsoft says that multibyte versions of C runtime functions support UTF-8 after April 2018 update and that you should link statically if you wish to support older window versions.  See

https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/setlocale-wsetlocale?view=msvc-160#utf-8-support

Pretty cool!
