### ISSUE TITLE
`opendir` doesn't handle path string properly with Russian localization.

### ISSUE THREAD

**Issue by paladin-t** [tronkko/dirent#47]
`opendir` doesn't handle path string properly with Russian localization.

OS: Windows 7

Localization: Russian

Steps to reproduce it:

    * (Important) Set your Windows' formatting localization to Russian in the Control Panel
    * Pass "Мои Документы" (My Documents in Russian) to `opendir`
    * You'll find `mbstowcs_s` doesn't convert it correctly

```c
/* Open directory stream using plain old C-string */
static DIR *opendir(const char *dirname)
{
	...

	/* Convert directory name to wide-character string */
	wchar_t wname[PATH_MAX + 1];
	size_t n;
	int error = mbstowcs_s(&n, wname, PATH_MAX + 1, dirname, PATH_MAX+1);
	if (error)
		goto exit_failure;

	...
}
```

Possible fix: use `MultiByteToWideChar` instead of `mbstowcs_s`

```c
/* Open directory stream using plain old C-string */
static DIR *opendir(const char *dirname)
{
	...

	/* Convert directory name to wide-character string */
	wchar_t wname[PATH_MAX + 1];
	int written = MultiByteToWideChar(CP_ACP, 0, dirname, -1, wname, PATH_MAX + 1);
	if (written == 0)
		goto exit_failure;

	...
}
```

**Comment by tronkko** [comment]
Does your program set any specific locale when it starts?  Like https://github.com/tronkko/dirent#how-to-enable-utf-8-support

**Comment by tronkko** [comment]
How do you pass the directory name to opendir?  Like with argc & argv command line arguments or do you scan the parent directory and then descend to subdirectory which doesn't open?

**Comment by paladin-t** [comment]
Thank you for your reply. Here's the full story, I'm using dirent in one of my project to handle directory traversing. The software implements an "Open Directory" feature, the directory argument was passed from some open-directory-dialog. This bug was reported by a Russian user (Win 7). Yes I am using setlocale to properly handle encoding, I made a minimal test program to reproduce it. And I simplified it to pass the argument via argc & argv. I also created a "Мои Документы" under the running root for test.

See [ConsoleApplication1.zip](https://github.com/tronkko/dirent/files/7787628/ConsoleApplication1.zip)

Before running it, change the system locale by:

![1](https://user-images.githubusercontent.com/2062224/147635348-e798c28e-12d2-400d-be8d-db8bf8d8d949.png)

![2](https://user-images.githubusercontent.com/2062224/147635371-bee2042e-58a2-4e99-a190-ba2aca2b828f.png)

![3](https://user-images.githubusercontent.com/2062224/147635390-89ce4c57-1b91-40f6-b275-b48a6be41932.png)

Wrong result:

![a](https://user-images.githubusercontent.com/2062224/147635409-40bc7adc-8c66-47e4-94d3-91282fa1db2d.png)

Expected result:

![b](https://user-images.githubusercontent.com/2062224/147635429-cc62629c-c4f5-4503-9205-7e09cab2a033.png)

I tested it under Russian, Chinese and English locales. As you see I'm using a Chinese setup myself, which makes it more interesting. Here's the full report:

## 1. Setting system locale to Russian

| setlocale | #include "dirent.h" | #include "dirent_mod.h" |
|---|---|---|
| setlocale(LC_ALL, "") | **Wrong** | Correct |
| setlocale(LC_ALL, "C") | **Wrong** | Correct |
| setlocale(LC_ALL, "LC_CTYPE=.utf8") | **Wrong** | Correct |

## 2. Setting system locale to Chinese

| setlocale | #include "dirent.h" | #include "dirent_mod.h" |
|---|---|---|
| setlocale(LC_ALL, "") | Correct | Correct |
| setlocale(LC_ALL, "C") | **Wrong** | Correct |
| setlocale(LC_ALL, "LC_CTYPE=.utf8") | **Wrong** | Correct |

When using Chinese locale, `opendir` recognizes the "Мои Документы" directory, the reason might be that the Chinese locale also includes Cyrillic pages.

## 3. Setting system locale to English

| setlocale | #include "dirent.h" | #include "dirent_mod.h" |
|---|---|---|
| setlocale(LC_ALL, "") | **Wrong** | Correct |
| setlocale(LC_ALL, "C") | **Wrong** | Correct |
| setlocale(LC_ALL, "LC_CTYPE=.utf8") | **Wrong** | Correct |

I don't like to fix bugs by "guessing", but in my experience it never makes mistake with `MultiByteToWideChar` and `WideCharToMultiByte` on Windows. I'm not an expert of unicode handling, it's pretty possible that I'm missing something. Maybe you can help to address the actual reason.

BTW. there is a similar issues with `wcstombs_s` in `readdir_r`, which I replaced with `WideCharToMultiByte` in dirent_mod.h.

Thank you again for your time!

**Comment by tronkko** [comment]
Thanks for reporting this issue!  Your fix for Windows 7 is propably valid and needed on Windows 7 where UTF-8 support isn't perfect.

If this issue still bothers you, I suggest you try to use wide-character versions of the dirent functions or convert file names to proper character set (e.g. UTF-8) in wmain function.  There is an example about that in the README.md file.  I have also updated the example programs to use UTF-8.
