### ISSUE TITLE
VC\include directory not found

### ISSUE THREAD

**Issue by sevstels** [tronkko/dirent#60]
Microsoft Visual Studio 2010
for _WIN64, file added locally. 
Tried it, it doesn't work, lots of errors:

dirent.h(422): warning C4067: unexpected tokens following preprocessor directive - expected a newline
 dirent.h(422): warning C4067: unexpected tokens following preprocessor directive - expected a newline
 dirent.h(443): warning C4067: unexpected tokens following preprocessor directive - expected a newline
 dirent.h(443): warning C4067: unexpected tokens following preprocessor directive - expected a newline
 dirent.h(406): error C2275: '_WDIR' : illegal use of this type as an expression dirent.h(281) : see declaration of '_WDIR'
 dirent.h(406): error C2065: 'dirp' : undeclared identifier
 dirent.h(407): error C2065: 'dirp' : undeclared identifier
 dirent.h(411): error C2065: 'dirp' : undeclared identifier
 dirent.h(411): error C2223: left of '->handle' must point to struct/union

**Comment by tronkko** [comment]
You might want to try an older version of dirent as you are using an old compiler.  See https://github.com/tronkko/dirent/releases

**Comment by sevstels** [comment]
I tried this with VS2019
similarly doesn't work...
maybe the problem is in the code?

**Comment by tronkko** [comment]
Does it compile if you create a new project?  I am wondering if this has something to do with project settings.

**Comment by sevstels** [comment]
1>C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\windef.h(126): warning C4005: 'APIENTRY' : macro redefinition
GLFW/glfw3.h(123) : see previous definition of 'APIENTRY'

filebrowser\dirent.h(422): warning C4067: unexpected tokens following preprocessor directive - expected a filebrowser\dirent.h(422): warning C4067: unexpected tokens following preprocessor directive - expected a newline
filebrowser\dirent.h(443): warning C4067: unexpected tokens following preprocessor directive - expected a newline
filebrowser\dirent.h(443): warning C4067: unexpected tokens following preprocessor directive - expected a newline

**Comment by tronkko** [comment]
I pushed an update for warning C4067, see https://github.com/tronkko/dirent/commit/47480bb729db38120a5c0b6f1e201abf0982f6a8 Does it help?

I still suspect that the long list of errors is caused by C89 mode.  In project settings, can you enable Microsoft extensions or otherwise choose a different mode?

**Comment by sevstels** [comment]
It compiles and even works, but adds warnings. I have put it off for now, I will use another method.

**Comment by sevstels** [comment]
I fix this errors by loading 2 additional files from https://github.com/tpn/winsdk-10/
They contain the definition of the WINAPI_FAMILY_PARTITION macro
#include <winapifamily.h>
winpackagefamily.h
