### ISSUE TITLE
Include scandir as well?

### ISSUE THREAD

**Issue by neaflo** [tronkko/dirent#7]
Hi guys,

Would be nice if you include [scandir] in the <dirent.h> as well. It is defined in a newer POSIX standard here http://pubs.opengroup.org/onlinepubs/9699919799/. And found an implementation of scandir here http://www.fltk.org/strfiles/1779/scandir.c

I'm using <dirent.h> to compile libconfig in Windows and they use scandir in the implementation. 

Thanks

**Comment by AraHaan** [comment]
I need to use this to compile git in Visual Studio 2015 so I can make git.exe only to make an installer that just drops git in ``%SystemDrive%\Windows`` and/or ``%SystemDrive%\Windows\SysWOW64`` (if 64 bit windows) so it can add git to the path on Window 7's command prompt without requiring mingw or cygwin installed to make the most of git. (So a pure windows build of git for windows basically). This unfortunately means an absolute need for things like this and to hopefully minimize the patching for it as much as possible.

**Comment by tronkko** [comment]
Moved AraHaan's comment to issue https://github.com/tronkko/dirent/issues/9

**Comment by tronkko** [comment]
Scandir is now included.  Please have a try!
