### ISSUE TITLE
PATH_MAX not defined in find.c

### ISSUE THREAD

**Issue by DDHarry** [tronkko/dirent#8]
Hello Toni,

Thanks for the libs. Good job.

I am using MacOS X, clang compiler. When trying to compile find.c, it rejects it because of
  'PATH_MAX not defined or used'

PATH_MAX seems to be the max length of the files & directories names listed. So I fix it to 255 and it just works fine.

I hope you spend a fantastic day.
Thanks,
Harry

**Comment by tronkko** [comment]
Glad you figured it out!

I trust that the problem will be fixed by authors of Clang in the near future so we don't need to define PATH_MAX in find.c.
